extends Node


enum CardEnum {NONE = -1, DIG_GROUND, PLANT_POTATO, PLANT_ONION, PLANT_PEAS, PLANT_BEET, PLANT_CABBAGE, PLACE_SPRINKLER}

enum GroundTileEnum {EMPTY = -1, DIRT, SOIL, POTATO, ONION, PEAS, BEET, CABBAGE, SPRINKLER}
enum EffectsEnum {EMPTY = -1, DEAD, WATER_1, WATER_2, WATER_3}
enum UITileEnum {EMPTY = -1, HIGHLIGHT, INVALID}
