extends Node


enum CardEnum {SOW_GROUND, PLANT_POTATO, PLANT_ONION, PLANT_LEGUMEN, PLANT_ROOT, PLANT_BRASSICA, PLACE_SPRINKLER}
enum GroundTileEnum {EMPTY = -1, DIRT, SOIL, POTATO, ONION, LEGUMEN, ROOT, BRASSICA, SPRINKLER}
enum UITileEnum {EMPTY = -1, HIGHLIGHT}
