extends Node


enum CardEnum {SOW_GROUND, PLANT_POTATO, PLANT_ONION, PLANT_PEAS, PLANT_BEET, PLANT_CABBAGE, PLACE_SPRINKLER}
enum GroundTileEnum {EMPTY = -1, DIRT, SOIL, POTATO, ONION, PEAS, BEET, CABBAGE, SPRINKLER}
enum UITileEnum {EMPTY = -1, HIGHLIGHT, INVALID}
